  
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: [self-hosted, Windows]

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
      
    - name: Set up JDK 1.11
      if: env.JAVA_HOME == 'C:\Program Files\AdoptOpenJDK\jdk-11.0.9.11-hotspot'
      uses: actions/setup-java@v1
      with:
        java-version: 1.11         
     
    - name: Build with Gradle
      run: ./gradlew build